spring:
  application:
    name: eureka-server

server:
  port: 7001

eureka:
  instance:
    hostname: peer1
  client:
    # 是否将自己注册到eureka server，默认为true
    register-with-eureka: true
    # 是否从eureka-sever 获取注册信息。默认为true
    fetch-registry: true
    # 设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址。默认是 http://localhost:8761/eureka ；多个地址可使用英文逗号（,）分隔。
    service-url:
      defaultZone: http://peer2:7002/eureka/