spring:
  datasource:
    url: jdbc:mysql://192.168.199.120:3306/db_demo
    username: root
    password: WINDeaker@0917
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: mybatis.simple.pojo
  mapper-locations: classpath:mapper/*.xml