spring:
  redis:
    # 主机
    host: 192.168.199.120
    # 端口
    port: 6379
    # 数据库编号
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数，-1 表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间，-1表示没有限制
        max-wait: -1
        # 最大空闲连接
        max-idle: 8
        # 最小空闲连接
        min-idle: 0

