spring:
  application:
    name: eureka-7002
server:
  port: 7002
eureka:
  instance:
    hostname: eureka7003.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7004.com:7004/eureka/,http://eureka7003.com:7003/eureka/