server:
  port: 7023

spring:
  application:
    name: eureka-consumer-hello-typec
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
    # 是否启用服务注册与发现，默认为true
    enabled: true