spring:
  datasource:
    username: root
    password: WINDeaker@0917
    url: jdbc:mysql://192.168.199.120:3306/sql_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver